config/routes.rb
Rails.application.routes.draw do
  resources :menus
  resources :orders
  resources :line_items
  resources :carts
  mount RailsAdmin::Engine => '/negroniadminstore', as: 'rails_admin'
  get "product/index"
  resources :categories
  resources :products

  root 'products#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	validates :name, :address, :email,  presence: true
	validates :phone, numericality: { only_integer: true }
	validates :email, confirmation: true
  validates_format_of :email, :with => /@/
  
  
	
	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
			item.cart_id = nil
			line_items << item
		end
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:new, :create]
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    if @cart.line_items.empty?
      redirect_to root_path, notice: "Ваша корзина пуста"
      return 
    end
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(@cart)

    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        OrderNotifier.received(@order).deliver
        format.html { redirect_to root_path, notice:
            'Спасибо за ваш заказ.' }
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        #@cart = current_cart
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :lastname, :phone, :address, :email)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<!-- Yandex.Metrika counter --> <script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter37683945 = new Ya.Metrika({ id:37683945, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true, trackHash:true, ecommerce:"dataLayer" }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks"); </script> <noscript><div><img src="https://mc.yandex.ru/watch/37683945" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->
<div class="checkout">
          <div class="container">
          <!-- Heading -->
          <h4>Оформление заказа</h4>
            <div class="row">
              <div class="col-md-7 col-sm-6">
                <!-- Checkout Form -->
  <%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

                <form class="form-horizontal" role="form">
                  <div class="form-group">
                    
                    <div class="col-md-8">
                      <%= f.text_field :name, :class => "form-control", :placeholder => "Имя" %>
                    </div>
                  </div>    
                  <div class="form-group">
                    
                    <div class="col-md-8">
                      <%= f.text_field :lastname, :class => "form-control", :placeholder => "Фамилия" %>
                    </div>
                  </div>          
                  <div class="form-group">
                    
                    <div class="col-md-8">
                       <%= f.text_area :address, :class => "form-control", :placeholder => "Адрес" %>

                    </div>
                  </div>
                  <div class="form-group">
                    
                    <div class="col-md-8">
                      <%= f.text_field :phone, :class => "form-control", :placeholder => "Телефон"  %>
                    </div>
                  </div>
                  <div class="form-group">
                    
                    <div class="col-md-8">
                      <%= f.text_area :commit, :class => "form-control", :placeholder => "Коментарий к заказу"  %>
                    </div>
                  </div>
                  

                  <div class="form-group">
                    
                    <div class="col-md-8">
                       <%= f.text_field :email, :class => "form-control", :placeholder => "E-Mail" %>
                    </div>
                  </div>
                  
                  
                  <div class="form-group">
                    <div class="col-md-offset-2 col-md-8">
                      <%= f.submit 'Подтверждение заказа', :class => "btn btn-danger btn-sm" %>
                      <button type="reset" class="btn btn-default btn-sm">Reset</button>
                    </div>
                  </div>
                  
                </form>
              <% end %>
              </div>
              <div class="col-md-5 col-sm-6">
                <!-- Checkout sidebar items -->
                <div class="sidebar-item">
                  <!-- Heading -->
                  <h5 class="pull-left">Бесплатная доставка</h5>
                  <!-- Sidebar content icon -->
                  <i class="fa fa-truck br-green pull-right"></i>
                  <div class="clearfix"></div>
                  <!-- Sidebar Paragraph -->
                  <p>Доставка суши, роллов, темаки и других блюд японской кухни к Вашему столу! Мы максимально оперативно доставим Ваш заказ суши в любую точку Бельц. Бесплатно доставляются заказы: от 300 лей по городу доставка бесплатная!</p>
                </div>
                <!-- Checkout sidebar items -->
                
              </div>
            </div>
          </div>
        </div>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.lastname %></td>
        <td><%= order.phone %></td>
        <td><%= order.address %></td>
        <td><%= order.email %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<%= render 'form' %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @order.lastname %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @order.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>