config/routes.rb
Rails.application.routes.draw do
  resources :menus
  resources :orders
  resources :line_items
  resources :carts
  mount RailsAdmin::Engine => '/negroniadminstore', as: 'rails_admin'
  get "product/index"
  resources :categories
  resources :products

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
	
	belongs_to :category
	has_many :line_items

	mount_uploader :image, ImageUploader
	
	before_destroy :ensure_not_referenced_by_any_line_item

	validates :name, :category_id, :image, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}


	def self.latest
   Product.order(:updated_at).last
	end

	private
	# убеждаемся в отсутствии товарных позиций, ссылающихся на данный товар
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'существуют товарные позиции')
      return false
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  include CurrentCart
  before_action :set_cart
  # GET /products
  # GET /products.json
  def index
    @products = Product.order(:name)
   # @cart = Cart.find(session[:cart_id])
   #@cart = current_cart
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :ingridient, :description, :image, :category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :ingridient %><br>
    <%= f.text_field :ingridient %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name, :prompt => true  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product_row.html.erb
<!-- Yandex.Metrika counter --> <script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter37683945 = new Ya.Metrika({ id:37683945, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true, trackHash:true, ecommerce:"dataLayer" }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks"); </script> <noscript><div><img src="https://mc.yandex.ru/watch/37683945" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->
<% cache ['entry', product] do %>
<div class="col-md-3 col-sm-6 col-xs-12">
  <!-- Shopping items -->
  <div class="shopping-item">
    <!-- Image -->
    <div class="gallery-content">

      <div class="element">
        <!-- Image -->
        <%= image_tag(product.image, class: 'img-responsive') %>
        <!-- Shopping item name / Heading -->
        <!-- Gallery Image Hover Effect -->
        <span class="gallery-img-hover"></span>
        <!-- Gallery Image Hover Icon -->
        <a href=" <%= image_path(product.image) %>" class="gallery-img-link">
          <i class="fa fa-search-plus hover-icon icon-left"></i>
        </a>

        <%= link_to product_path(product) do %>
        <i class="fa fa-link hover-icon icon-right"></i>
        <% end %>

      </div>
    </div>
    
    <h4 class="pull-left"><%= product.name %></h4>
    <span class="item-price pull-right"><%= product.price %> MDL</span>
    <div class="clearfix"></div>
    <!-- Paragraph -->
    <p><%= product.ingridient %>.</p>
    <!-- Buy now button -->
   
    <div class="visible-xs">
    </div>
    <!-- Shopping item hover block & link -->
    <div class="input-group">
     
      <div class="input-group-btn">
       
        <%= button_to 'В корзину', line_items_path(product_id: product),class: "btn btn-danger btn-sm",remote: true %>
       
      </div>
    </div>  
  
  </div>
</div>
<div class="clearfix visible-xs"></div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% cache ['product', Product.latest] do %>
	<% @products.each do |product| %>
		<%= render "product_row", product: product %>
	<% end %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-4 col-sm-5">
    <!-- Product image -->
    <%= image_tag(@product.image, class: 'img-responsive img-thumbnail') %>
  </div>
  <div class="col-md-8 col-sm-7">
    <!-- Heading -->

    <h3><%= @product.name %> </h3> 
    <h4>Цена: <%= @product.price %> лей</h4>
    <div class="row">
      <div class="col-md-7 col-sm-12">
        <!-- Single item details -->
        <div class="item-details">
          <!-- Paragraph -->
          <h5>Ингридиеты :-</h5>
          <p class="text-justify"><%= @product.ingridient %>.</p>
          <!-- Heading -->
          <h5>Описание :-</h5>
          <p class="text-justify"><%= @product.description %>.</p>
          <!-- Recipe ingredients -->
        </div>
        </tr>
        <div class="social">
          <a class="facebook", onclick="Share.facebook('URL','TITLE','IMG_PATH','DESC')"><i class="fa fa-facebook"></i></a>
          <a class="vk", onclick="Share.vkontakte('URL','TITLE','IMG_PATH','DESC')"><i class="fa fa-vk"></i></a>
          <a class="twitter", onclick="Share.twitter('URL','TITLE','IMG_PATH','DESC')"><i class="fa fa-twitter"></i></a>
          <a class="od", onclick="Share.odnoklassniki('URL','DESC')"><i class="fa fa-odnoklassniki "></i></a>            

        </div>
      </div>


      
    </div><!--/ Inner row end  -->
  </div>
</div>

<!-- Shopping item hover block & link -->